[package]
name = "rmake"
version = "0.1.0"
authors = ["Irisawa Masaru <mass10.github@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "*"
serde_derive = "*"
toml = "*"
