[settings]
email = "administrator@example.com"
threshold = 2147483647
attributes.attribute01 = "属性01"
unknown_attribute = true

[[steps]]
name = "my-app"
depends_on = ["my-lib"]
command = ["yarn", "install"]

[[steps]]
name = "my-lib"
depends_on = ["ステップ1"]
command = ["yarn", "workspace", "my-lib", "tsc", "--build"]
