[settings]
email = "administrator@example.com"
threshold = 2147483647
attributes.attribute01 = "属性01"
unknown_attribute = true

#
# アプリケーション本体をビルドします。
#
[[tasks]]
description = "アプリケーション本体のビルド"
name = "my app"
depends_on = ["install", "my lib"]
command = ["yarn", "install"]

#
#
#
[[tasks]]
name = "install"
depends_on = []
command = ["yarn", "install"]

#
#
#
[[tasks]]
name = "my lib"
depends_on = []
command = ["yarn", "workspace", "my-lib", "tsc", "--build"]

#
#
#
[[tasks]]
name = "reserved step"
depends_on = ["undefined step"]
command = ["DIR"]
