[env]
ENV01 = "administrator@example.com"
ENV02 = "2147483647"
ENV03 = "true"

#
# アプリケーション本体をビルドします。
#
[[tasks]]
description = "アプリケーション本体のビルド"
name = "my-application"
depends_on = ["install", "my-lib-a", "my-lib-b"]
command = ["yarn", "install"]

#
# ワークスペースを更新します。
#
[[tasks]]
description = "セットアップタスクです。"
name = "install"
depends_on = []
command = ["yarn", "install"]

#
# 共通ライブラリ A をビルドします。
#
[[tasks]]
name = "my-lib-a"
depends_on = ["common"]
command = ["yarn", "workspace", "my-lib-a", "tsc", "--build"]

#
# コア共通モジュールをビルドします。
#
[[tasks]]
name = "common"
depends_on = []
command = ["yarn", "workspace", "common", "tsc", "--build"]

#
# 共通ライブラリ B をビルドします。
#
[[tasks]]
name = "my-lib-b"
depends_on = ["common"]
command = ["yarn", "workspace", "my-lib-b", "tsc", "--build"]
