[env]
MY_ENV_01 = "administrator@example.com"
MY_ENV_02 = "2147483647"
MY_ENV_03 = "true"

[[tasks]]
description = "テスト"
name = "test1"
depends_on = []
command = [
	["echo", "%MY_ENV_02%"],
	["echo", "$MY_ENV_02"],
]
